# This is a basic workflow to help you get started with Actions

name: Translate to Dutch
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ "quote" ]
  pull_request:
    branches: [ "quote" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get files from repo
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        
      - name: Install dependencies
        run: pip3 install googletrans==4.0.0rc1 argostranslate
        
      - name: Run Python from 0 to 1000
        run: python main.py 0 1000
        
      - name: Run Python from 1000 to 2000
        run: python main.py 1000 2000
        
      - name: Run Python from 2000 to 3000
        run: python main.py 2000 3000
        
      - name: Run Python from 3000 to 4000
        run: python main.py 3000 4000
        
      - name: Run Python from 4000 to 5000
        run: python main.py 4000 5000
        
      - name: Commit files
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add --all
          if [-z "$(git status --porcelain)"]; then
            echo "::set-output name=push::false"
          else
            git commit -m "Add changes" -a
            echo "::set-output name=push::true"
          fi
        shell: bash
      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
